version: '3.5'
services:
    # DB Service
    db:
        image: mysql:8.0
        container_name: tasks_db
        restart: unless-stopped
        tty: true
        ports:
            - "3306"
        environment:
            MYSQL_DATABASE: "tasks_db"
            MYSQL_ROOT_PASSWORD: "Jay#254701437909"
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - ./compose_configs/mysql/my.cnf:/etc/mysql/my.cnf
            - ./compose_configs/mysql-files:/var/lib/mysql-files
        networks:
            - app-network

    # APP Service
    api:
        build:
            context: .
            dockerfile: Dockerfile
        #image: php:8.1
        container_name: tasks_api
        restart: unless-stopped
        tty: true
        ports:
            - "8051:8051"
        depends_on:
            - db
        environment:
            SERVICE_NAME: tasks_app_code
            SERVICE_TAGS: dev
        working_dir: /var/www/html/
        volumes:
            - ./:/var/www/html/
            - ./compose_configs/php/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
            - /var/www/html/vendor
            - /var/www/html/node_modules
        networks:
            - app-network

        # SPA Service
    frontend:
        build:
            context: ./io_spa
            dockerfile: Dockerfile
        image: node:latest
        container_name: tasks_frontend
        restart: unless-stopped
        tty: true
        depends_on:
            - api
        ports:
            - "8050:8050"
        volumes:
            - ./io_spa:/var/www/html/
            - /var/www/html/node_modules
            - /var/www/html/dist/spa
        networks:
            - app-network

# Docker Networks
networks:
    app-network:
        name: app-network
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
